name: Build & commit
on: push
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make docs
        run: make all
      - name: Commit files
        run: |
          git config --global user.name 'dde-fite's github action'
          git config --global user.email 'dde-fite@users.noreply.github.com'
          git commit -am "Make pandoc"
          git push
