name: Build & commit
on: push
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTION_TOKEN }}
      - name: Setup Pandoc and LaTeX
        uses: pandoc/actions/setup@v1
        with:
          version: latest
      - name: Install LaTeX fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-fonts-extra
      - name: Make docs
        run: make all
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          commit_message: make documentation
